### ISSUE TITLE
Why do we need to specify `2034438 lovelace` in `lobster-contribute.sh`? 

### ISSUE THREAD

**Issue by ahaxu** [input-output-hk/lobster-challenge#5]
This is not an issue actually, I just wanna ask to understand more.
Why do we need to specify exactly `2034438 lovelace` in this line https://github.com/input-output-hk/lobster-challenge/blob/main/scripts/lobster-contribute.sh#L65 . Can we use different amount of lovelace?

```
...
--tx-out "$scriptAddr + 2034438 lovelace + $nftValue + $counterValue + $votesValue" \
...
```

**Comment by Zagita21** [comment]
because of minimum Ada requirements
